name: karobar
description: "Android App for Karobar"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  cupertino_icons: ^1.0.8
  #charts_flutter: ^0.12.0
  fl_chart: ^0.65.0
  intl: ^0.18.0
  http: ^1.2.1
  web: ^1.0.0
  provider: ^6.1.2
  build_runner: ^2.4.7
  lucide_icons_flutter  : ^1.2.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.0.4
  qr_flutter: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  go_router: ^13.0.0


flutter:
  uses-material-design: true

  assets:
    - lib/assets/
    - lib/assets/image2.png
    - lib/assets/logoR.png


