List<Map<String, dynamic>> foodItems = [
  {'ItemID': 'Rest1001250001', 'name': 'Spring Rolls', 'price': 150, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Chinese']},
  {'ItemID': 'Rest1001250002', 'name': 'Chicken Tikka', 'price': 250, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Indian']},
  {'ItemID': 'Rest1001250003', 'name': 'Pasta Alfredo', 'price': 300, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'ItemID': 'Rest1001250004', 'name': 'Paneer Butter Masala', 'price': 200, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250005', 'name': 'Fried Rice', 'price': 180, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'ItemID': 'Rest1001250006', 'name': 'Caesar Salad', 'price': 120, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'ItemID': 'Rest1001250007', 'name': 'Veg Manchurian', 'price': 190, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'ItemID': 'Rest1001250008', 'name': 'Chicken Curry', 'price': 220, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250009', 'name': 'Garlic Bread', 'price': 100, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'ItemID': 'Rest1001250010', 'name': 'Shahi Paneer', 'price': 240, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250011', 'name': 'Chow Mein', 'price': 150, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'ItemID': 'Rest1001250012', 'name': 'Grilled Chicken', 'price': 350, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'ItemID': 'Rest1001250013', 'name': 'Hakka Noodles', 'price': 160, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'ItemID': 'Rest1001250014', 'name': 'Butter Chicken', 'price': 300, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250015', 'name': 'Margherita Pizza', 'price': 250, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'ItemID': 'Rest1001250016', 'name': 'Fish Curry', 'price': 270, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250017', 'name': 'Tomato Soup', 'price': 90, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'ItemID': 'Rest1001250018', 'name': 'Paneer Tikka', 'price': 200, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Indian']},
  {'ItemID': 'Rest1001250019', 'name': 'Sweet Corn Soup', 'price': 100, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Chinese']},
  {'ItemID': 'Rest1001250020', 'name': 'Lamb Chops', 'price': 400, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'ItemID': 'Rest1001250021', 'name': 'Schezwan Fried Rice', 'price': 190, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
  {'ItemID': 'Rest1001250022', 'name': 'Rogan Josh', 'price': 280, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250023', 'name': 'Chicken Satay', 'price': 220, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Continental']},
  {'ItemID': 'Rest1001250024', 'name': 'Dal Makhani', 'price': 180, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250025', 'name': 'Veg Biryani', 'price': 170, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250026', 'name': 'Egg Curry', 'price': 200, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Indian']},
  {'ItemID': 'Rest1001250027', 'name': 'Thai Green Curry', 'price': 320, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'ItemID': 'Rest1001250028', 'name': 'Momos', 'price': 110, 'image': 'lib/assets/image2.png', 'category': ['Starters', 'Chinese']},
  {'ItemID': 'Rest1001250029', 'name': 'Grilled Salmon', 'price': 450, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Continental']},
  {'ItemID': 'Rest1001250030', 'name': 'Veg Hakka Noodles', 'price': 150, 'image': 'lib/assets/image2.png', 'category': ['Main Course', 'Chinese']},
];
